#!/usr/bin/env bash
#
# Generates the .env files a fresh clone needs, with real random secrets.
#
#   ./scripts/bootstrap.sh          # create anything missing
#   ./scripts/bootstrap.sh --force  # overwrite existing files (destructive)
#
# Safe to re-run: existing files are left alone unless --force is passed, so it
# will never clobber credentials you have already filled in.
#
# What it creates:
#   .env       root — docker compose reads this for ${VAR} substitution
#   api/.env   the API process reads this inside its container
#
# Secrets are generated with openssl, so the passwords and JWT secret are
# unique per install. Nothing here contacts a payment gateway — you still add
# your own Razorpay/Stripe keys before taking real money.
set -euo pipefail

cd "$(dirname "$0")/.."

FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true

green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

rand() {
  # 32 hex chars: long enough for a JWT secret, safe in a URL / connection
  # string (no shell- or DSN-special characters to escape).
  openssl rand -hex "${1:-16}"
}

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate secrets" >&2
  exit 1
fi

POSTGRES_PASSWORD="$(rand 16)"
JWT_SECRET="$(rand 32)"
ADMIN_PASSWORD="$(rand 8)"

# ── root .env ────────────────────────────────────────────────────────────────
if [[ -f .env && "$FORCE" == false ]]; then
  yellow "•  .env already exists — leaving it alone"
  # Reuse the existing password so api/.env stays consistent with it.
  POSTGRES_PASSWORD="$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2- || true)"
  : "${POSTGRES_PASSWORD:=$(rand 16)}"
else
  cat > .env <<EOF
# Generated by scripts/bootstrap.sh — safe to edit.
# Read by docker compose for \${VAR} substitution in docker-compose.yml.
POSTGRES_USER=marketkit
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=marketkit
PORT=3000
EOF
  green "✓  wrote .env"
fi

# ── api/.env ─────────────────────────────────────────────────────────────────
if [[ -f api/.env && "$FORCE" == false ]]; then
  yellow "•  api/.env already exists — leaving it alone"
else
  cat > api/.env <<EOF
# Generated by scripts/bootstrap.sh — safe to edit.
# Read by the API process. See api/.env.example for every supported variable.

APP_ENV=development
PORT=3000

# Points at the 'postgres' service inside the compose network. Running the API
# outside Docker? Change the host to localhost and the port to 5433.
DATABASE_URL=postgres://marketkit:${POSTGRES_PASSWORD}@postgres:5432/marketkit?sslmode=disable

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=8h

# First-boot admin. Change the password after you log in.
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_FIRST_NAME=Demo
ADMIN_LAST_NAME=Admin

# Mailhog catches every outgoing email in dev — open http://localhost:8025
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_SECURE=false
SMTP_FROM=noreply@example.com

CORS_ORIGIN=http://localhost:5173,http://localhost:8081

# ── Payments ────────────────────────────────────────────────────────────────
# The kit runs one currency per deployment; all *_minor columns hold this
# currency's minor unit (paise for INR, cents for USD).
PAYMENT_PROVIDER=razorpay
PAYMENT_CURRENCY=INR

# Add your own test keys before trying a payment. Left empty the API starts
# fine and fails with a clear error only when a payment is attempted.
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=

UPLOAD_DIR=./uploads
EOF
  green "✓  wrote api/.env"
  echo
  green "   admin login:  admin@example.com  /  ${ADMIN_PASSWORD}"
fi

echo
green "Bootstrap complete."
echo "Next:  make up        # start everything"
echo "       make seed-demo # fill the database with demo data"
